{% set name = "flowrep" %}
{% set version = "0.1.9" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flowrep-{{ version }}.tar.gz
  sha256: 917c0a1ed78c13c07570efe6464a44240c0b0024361d1132e54eeb239b57904d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - hatchling
    - hatch-vcs
    - pip
  run:
    - networkx >=3.4.2,<3.7.0
    - python >={{ python_min }},<3.15
    - numpy >=2.3.0,<2.5.0
    - pydantic

test:
  imports:
    - flowrep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/flowrep/
  summary: flowrep - Your premier tool for workflow representations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
