{% set name = "flowrep" %}
{% set version = "0.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flowrep-{{ version }}.tar.gz
  sha256: 1ddf5fbe672c88ce77a0161a12551056101dd0dd82b3b02a5e845ecec08d45b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - setuptools >=68.0.0
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }},<3.14
    - numpy >=2.3.0,<2.4.0
    - semantikon >=0.0.20,<=0.0.21

test:
  imports:
    - flowrep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/flowrep/
  summary: flowrep - Your premier tool for workflow representations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
