{% set name = "flowrep" %}
{% set version = "0.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flowrep-{{ version }}.tar.gz
  sha256: 9e0b06ee5def65b40d5899b033d4e35e16e1c8007b77c3a065a17e3bbc618d3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - networkx >=3.4.2,<3.7.0
    - python >={{ python_min }},<3.15
    - pydantic >=2.12.0,<2.13.0
    - pyiron_snippets >=1.2.1,<2.0.0

test:
  imports:
    - flowrep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/flowrep/
  summary: flowrep - Your premier tool for workflow representations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
    - liamhuber
